def COLOR_MAP = [
  'SUCCESS' : 'good',
  'FAILURE' : 'danger'
]
pipeline{
  agent any 
   environment{
    cluster=  "vproappprod"    
    service=  "vproappprodsvc"               
    }

  stages{
 stage('deploy to prod ecs stage'){
    steps {
        withAWS(credentials: 'awscreds' , region:'us-east-1'){
           sh ' aws ecs update-service --cluster ${cluster} --service ${service}  --force-new-deployment '  

        } 
    }

 }

  }
  post {
        always  {
            echo 'slack notification.'
            slackSend channel: '#cicdjenkins',
            color:  COLOR_MAP[currentBuild.currentResult],
            message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n for more info visit : ${env.BUILD_URL} " 
        }
  }

}  